#!/usr/bin/env bash
# Symmetric uninstaller. Removes the install dir, wrappers, and rc edits.
set -euo pipefail

_MARK_BEGIN='# >>> prune (https://github.com/soyruiz/Prune) >>>'
_MARK_END='# <<< prune (https://github.com/soyruiz/Prune) <<<'

usage() {
    cat <<EOF
Prune uninstaller.

Usage:
  ./uninstall.sh [options]

Options:
  --prefix DIR    install prefix used at install time
                  (default: \$XDG_DATA_HOME or ~/.local/share)
  --bin DIR       bin dir used at install time
                  (default: ~/.local/bin)
  --dry-run       show what would be removed without making changes
  -h, --help      this help
EOF
}

PREFIX="${XDG_DATA_HOME:-$HOME/.local/share}"
BIN="$HOME/.local/bin"
DRY=0

while (( $# > 0 )); do
    case "$1" in
        --prefix)  PREFIX="$2"; shift 2 ;;
        --bin)     BIN="$2"; shift 2 ;;
        --dry-run) DRY=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) printf 'uninstall.sh: unknown option %s\n' "$1" >&2; exit 2 ;;
    esac
done

DEST="$PREFIX/prune"

remove() {
    if (( DRY == 1 )); then
        printf '  [dry-run] rm -rf %s\n' "$1"
    else
        rm -rf "$1"
    fi
}

# Wrappers we may have installed. We don't read $DEST/adapters/ because that
# may already be gone; instead we glob $BIN for *-prune scripts that point at
# our binary and remove only those.
remove_wrappers() {
    local wrapper
    for wrapper in "$BIN"/*-prune; do
        [[ -e "$wrapper" ]] || continue
        if grep -q "auto-generated by Prune installer\|Auto-generated by Prune" "$wrapper" 2>/dev/null; then
            remove "$wrapper"
        fi
    done
}

# Strip the marker block from a single rc file, in place. Idempotent.
strip_rc() {
    local rc="$1"
    [[ -f "$rc" ]] || return 0
    if ! grep -q "$_MARK_BEGIN" "$rc"; then
        return 0
    fi
    if (( DRY == 1 )); then
        printf '  [dry-run] strip prune block from %s\n' "$rc"
        return 0
    fi
    local tmp
    tmp=$(mktemp)
    awk -v b="$_MARK_BEGIN" -v e="$_MARK_END" '
        $0 == b { skip = 1; next }
        $0 == e { skip = 0; next }
        skip != 1
    ' "$rc" > "$tmp"
    # Trim trailing blank lines that the marker block may have left behind.
    awk 'BEGIN{n=0} {a[NR]=$0; if($0!="")last=NR} END{for(i=1;i<=last;i++) print a[i]}' "$tmp" > "${tmp}.2"
    mv "${tmp}.2" "$rc"
    rm -f "$tmp"
}

remove_wrappers
remove "$BIN/prune"
remove "$DEST"
for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
    strip_rc "$rc"
done

if (( DRY == 1 )); then
    printf '\nDry-run complete. No changes written.\n'
else
    printf '\n✓ Uninstalled Prune.\n'
fi
